"""
`keyword_const.py` is a list of keywords that are used to 
identify the computer science concepts in the text.
"""

COMPUTER_SCIENCE_KEYS = [
    "5g",
    "a-frame",
    "abyss web server",
    "access control",
    "accuracy",
    "accurev",
    "ada",
    "adafruit",
    "adaptive software development",
    "adguard home",
    "adobe experience cloud",
    "adonisjs",
    "affinity propagation",
    "agile",
    "agile unified process",
    "airbrake",
    "aix",
    "akamai",
    "aks",
    "alibaba cloud",
    "alibaba cloud container service",
    "alibaba cloud function compute",
    "alibaba cloud object storage service",
    "alibaba cloud resource orchestration service",
    "alienbrain",
    "aliyun",
    "allegro",
    "altair",
    "amazon elastic kubernetes service",
    "amazon web services",
    "amigaos",
    "android",
    "android studio",
    "angular",
    "angular cli",
    "anomaly detection",
    "ansible",
    "ant",
    "antivirus",
    "aolserver",
    "apache",
    "apache http server",
    "apache mesos",
    "apache spark",
    "apache thrift",
    "apache tomee",
    "apigee",
    "apollo",
    "appcelerator titanium",
    "appdynamics",
    "appium",
    "appsignal",
    "appveyor",
    "apriori algorithm",
    "araxis merge",
    "arch linux",
    "arduino",
    "arduino ide",
    "arnold shading language",
    "arx",
    "asana",
    "asd",
    "aso",
    "asp.net",
    "asp.net core",
    "assembla",
    "assembly",
    "association rule mining",
    "at&t cloud",
    "atom",
    "ats",
    "auc-pr",
    "auc-roc",
    "aup",
    "aurelia",
    "autoit",
    "automl",
    "avro",
    "awk",
    "aws",
    "aws amplify",
    "aws api gateway",
    "aws cloudformation",
    "aws cloudfront",
    "aws codecommit",
    "aws codepipeline",
    "aws eks",
    "aws elastic beanstalk",
    "aws iot",
    "aws lambda",
    "aws mobile",
    "aws s3",
    "awszabbix",
    "azure api management",
    "azure app service",
    "azure blob storage",
    "azure cdn",
    "azure devops",
    "azure functions",
    "azure kubernetes service",
    "azure monitor",
    "azure resource manager",
    "babel",
    "babylon.js",
    "backblaze b2",
    "backbone.js",
    "bagging",
    "baidu cloud",
    "balena",
    "bamboo",
    "bandwidth",
    "barracuda networks",
    "basecamp",
    "bash",
    "bass",
    "batch",
    "batch normalization",
    "bayesian inference",
    "bazaar",
    "beanstalk",
    "beego",
    "behat",
    "behave",
    "behavior driven development",
    "bem",
    "beos",
    "bert",
    "bias detection",
    "bias-variance tradeoff",
    "bigpanda",
    "bitbucket",
    "bitkeeper",
    "blazor",
    "ble",
    "bluejeans",
    "bluetooth",
    "bluetooth low energy",
    "blynk",
    "bmc truesight",
    "boa web server",
    "bokeh",
    "boo",
    "boosting",
    "bootstrap",
    "bottle",
    "bourbon",
    "bower",
    "box",
    "brocade",
    "browserify",
    "bsd sockets",
    "bugsnag",
    "bugzilla",
    "bulma",
    "business continuity",
    "c",
    "c#",
    "c# unity",
    "c++",
    "c++ maya",
    "ca unified infrastructure management",
    "cacti",
    "caddy",
    "caffe",
    "cakephp",
    "calabash",
    "canonical kubernetes",
    "canvas",
    "caprover",
    "cassandra",
    "catboost",
    "cayenne",
    "centos",
    "centurylink cloud",
    "ceph",
    "cern httpd",
    "cg",
    "chai",
    "chart.js",
    "check point",
    "chef",
    "cherokee",
    "cherrypy",
    "chrome os",
    "cidr",
    "circleci",
    "circuitpython",
    "cisco",
    "cisco cloud",
    "cisco intersight",
    "cisco networking equipment",
    "citrix cloud",
    "clearcase",
    "clion",
    "clojure",
    "clojurescript",
    "cloud foundry",
    "cloud networking",
    "cloudbric",
    "cloudflare",
    "cloudformation",
    "cloudfront",
    "cloudstack",
    "cloudwatch",
    "clustering",
    "cobol",
    "code co-op",
    "codeception",
    "codeclimate",
    "codecov",
    "codeigniter",
    "codeplex",
    "codeship",
    "codeship",
    "codeville",
    "coffeescript",
    "collabnet teamforge",
    "collaborative filtering",
    "common lisp",
    "compass",
    "concurrent versions system",
    "confusion matrix",
    "consul",
    "content delivery network",
    "content-based filtering",
    "contiki",
    "convolutional neural networks",
    "cordova",
    "cosine similarity",
    "couchbase",
    "coverity",
    "create react app",
    "cross-validation",
    "cryptography",
    "crystal",
    "crystal clear",
    "css",
    "css3",
    "cucumber",
    "cuda",
    "cvs",
    "cvsdude",
    "cvsnt",
    "cyber scm",
    "cyber threat analysis",
    "cyber threat assessment",
    "cyber threat attribution",
    "cyber threat collaboration",
    "cyber threat detection",
    "cyber threat feed",
    "cyber threat feed aggregator",
    "cyber threat feed analysis",
    "cyber threat feed api",
    "cyber threat feed automation",
    "cyber threat feed correlation",
    "cyber threat feed curation",
    "cyber threat feed distribution",
    "cyber threat feed enrichment",
    "cyber threat feed filtering",
    "cyber threat feed integration",
    "cyber threat feed management",
    "cyber threat feed marketplace",
    "cyber threat feed normalization",
    "cyber threat feed provider",
    "cyber threat feed quality control",
    "cyber threat feed standardization",
    "cyber threat feed subscription",
    "cyber threat feed validation",
    "cyber threat feed verification",
    "cyber threat hunting",
    "cyber threat information exchange",
    "cyber threat information sharing",
    "cyber threat intelligence",
    "cyber threat mitigation",
    "cyber threat modeling",
    "cyber threat monitoring",
    "cyber threat prevention",
    "cyber threat remediation",
    "cyber threat sharing",
    "cypress",
    "cython",
    "d3.js",
    "dad",
    "darcs",
    "darknet",
    "dart",
    "dash",
    "dask",
    "data augmentation",
    "data cleaning",
    "data preprocessing",
    "data visualization",
    "data wrangling",
    "datadog",
    "datagrip",
    "dbscan",
    "debian",
    "decision trees",
    "deep learning",
    "dell emc cloud",
    "deno",
    "density-based spatial clustering",
    "detox",
    "devicehive",
    "devops",
    "dhcp",
    "digitalocean",
    "digitalocean app platform",
    "digitalocean kubernetes",
    "digitalocean spaces",
    "dimensionality reduction",
    "directsound",
    "directx",
    "directx 12",
    "disaster recovery",
    "disciplined agile delivery",
    "distance metrics",
    "distributed concurrent versions system",
    "distributed file system",
    "distributed revision control system",
    "distributed version control system",
    "django",
    "dns",
    "docker",
    "docker compose",
    "docker hub",
    "docker swarm",
    "dokku",
    "domain driven design",
    "dragonfly bsd",
    "dropbox",
    "dropout",
    "dsdm",
    "dynamic systems development method",
    "dynamsoft scm anywhere",
    "dynatrace",
    "earlgrey",
    "echo",
    "eclipse",
    "eclipse paho",
    "edge computing",
    "eks",
    "elasticsearch",
    "electron",
    "elementary os",
    "elk stack",
    "elliptic envelope",
    "elm",
    "elmo",
    "emacs",
    "emacs lisp",
    "embedded amigaos",
    "embedded android",
    "embedded beos",
    "embedded dragonfly bsd",
    "embedded freebsd",
    "embedded freedos",
    "embedded haiku",
    "embedded ios",
    "embedded linux",
    "embedded ms-dos",
    "embedded netbsd",
    "embedded openbsd",
    "embedded os/2",
    "embedded plan 9",
    "embedded reactos",
    "embedded risc os",
    "embedded rtos",
    "embedded windows",
    "ember.js",
    "encryption",
    "ensemble learning",
    "envoy",
    "enzyme",
    "erlang",
    "eslint",
    "esp32",
    "esp8266",
    "espresso",
    "ethernet",
    "eucalyptus",
    "euclidean distance",
    "expectation-maximization",
    "explainability",
    "exploratory data analysis",
    "expo cli",
    "express.js",
    "extreme programming",
    "extreme programming",
    "f#",
    "f1 score",
    "f5 networks",
    "facebook messenger",
    "fairness",
    "fastapi",
    "fastly",
    "fasttext",
    "fdd",
    "feature driven development",
    "feature engineering",
    "feature selection",
    "fedora",
    "filecloud",
    "firebase",
    "firebase hosting",
    "fireeye",
    "firewall",
    "firewall technologies",
    "fisheye",
    "fission",
    "flask",
    "fluentd",
    "flutter",
    "fly",
    "fmod",
    "font awesome",
    "formal methods",
    "fortinet",
    "fortran",
    "fossil",
    "foundation",
    "fp-growth algorithm",
    "framework7",
    "freebsd",
    "freedos",
    "freertos",
    "ftp",
    "fuelphp",
    "fujitsu cloud",
    "g suite",
    "ganglia",
    "gatling",
    "gatsby",
    "gauge",
    "gcp",
    "gcpmicrosoft azure",
    "generative adversarial networks",
    "gensim",
    "gentoo",
    "gin",
    "git",
    "github",
    "gitlab",
    "gitlab ci/cd",
    "gke",
    "glassfish",
    "glowroot",
    "glsl",
    "glusterfs",
    "gnu arch",
    "gnu bazaar",
    "gnu rcs",
    "gnu revision control system",
    "go",
    "godot",
    "goland",
    "google app engine",
    "google cloud build",
    "google cloud cdn",
    "google cloud deployment manager",
    "google cloud endpoints",
    "google cloud functions",
    "google cloud iot",
    "google cloud monitoring",
    "google cloud platform",
    "google cloud source repositories",
    "google cloud storage",
    "google drive",
    "google kubernetes engine",
    "google web server",
    "google workspace",
    "gotomeeting",
    "gpt",
    "graalvm",
    "gradient boosting",
    "gradle",
    "grafana",
    "grafana loki",
    "graphql",
    "graylog",
    "gridsome",
    "groovy",
    "grpc",
    "grpc-gateway",
    "grpc-web",
    "grunt",
    "gtk",
    "gulp",
    "gunicorn",
    "gws",
    "h2o",
    "hadoop",
    "haiku",
    "hal",
    "hangouts",
    "haproxy",
    "harbor",
    "hashicorp terraform",
    "haskell",
    "hasura",
    "hateoas",
    "helix core",
    "heroku",
    "hiawatha",
    "hibernate",
    "hidden markov models",
    "hierarchical clustering",
    "highcharts",
    "hipchat",
    "hitachi cloud",
    "hlsl",
    "home assistant",
    "homebridge",
    "houdini vex",
    "hp-ux",
    "hpe cloud",
    "hpe oneview",
    "html",
    "html/css",
    "html5",
    "http",
    "https",
    "huawei cloud",
    "hudson",
    "hybrid recommender systems",
    "hyperapp",
    "hyperparameter tuning",
    "hypothesis testing",
    "ibm api connect",
    "ibm cloud",
    "ibm cloud automation manager",
    "ibm cloud functions",
    "ibm cloud kubernetes service",
    "ibm cloud monitoring",
    "ibm cloud object storage",
    "ibm cloud private",
    "ibm cloud storage",
    "ibm http server",
    "ibm i",
    "ibm jdk",
    "ibm rational clearcase",
    "ibm rational synergy",
    "ibm rational team concert",
    "ibm security",
    "ibm watson iot",
    "ibm websphere",
    "icinga",
    "icloud",
    "identity management",
    "ids/ips",
    "ifttt",
    "iis",
    "imap",
    "imperva",
    "in-app purchases",
    "incapsula",
    "incident response",
    "independent component analysis",
    "influxdb",
    "ini",
    "intel xdk",
    "intellij idea",
    "interpretability",
    "intrusion detection",
    "intrusion detection system",
    "intrusion prevention",
    "ionic",
    "ios",
    "ipv4",
    "ipv6",
    "iris",
    "ironfunctions",
    "ironruby",
    "isolation forest",
    "istio",
    "jaccard similarity",
    "jaeger",
    "jasmine",
    "java",
    "java awt",
    "java hotspot",
    "java servlets",
    "java swing",
    "javafx",
    "javascript",
    "javascript unity",
    "javaserver faces",
    "javaserver pages",
    "jboss",
    "jd cloud",
    "jenkins",
    "jest",
    "jetty",
    "jfrog artifactory",
    "jira",
    "jitsi",
    "jmeter",
    "joint application development",
    "jquery",
    "jquery mobile",
    "jruby",
    "jsf",
    "jshint",
    "jslint",
    "json",
    "json api",
    "julia",
    "juniper networks",
    "jupyter",
    "jupyter notebooks",
    "jython",
    "k-means clustering",
    "k-nearest neighbors",
    "kaa",
    "kakaotalk",
    "kali linux",
    "kallithea",
    "kalman filters",
    "kanban",
    "karma",
    "kemp technologies",
    "kendall correlation",
    "kendo ui",
    "keras",
    "kibana",
    "kingsoft cloud",
    "knative",
    "kohana",
    "kong",
    "kotlin",
    "kubeless",
    "kubernetes",
    "laminas",
    "laravel",
    "latency",
    "latent dirichlet allocation",
    "latex",
    "launchpad",
    "leaflet",
    "lean",
    "lean software development",
    "lede",
    "lenovo cloud",
    "lenovo xclarity",
    "less",
    "librenms",
    "libresource",
    "lightgbm",
    "lighttpd",
    "line",
    "linear regression",
    "linkerd",
    "linode",
    "linode kubernetes engine",
    "linux",
    "linux api",
    "lisp",
    "litelement",
    "litespeed",
    "litespeed web server",
    "load balancing",
    "loadbalancer.org",
    "loadrunner",
    "local outlier factor",
    "locust",
    "loggly",
    "logistic regression",
    "logrhythm",
    "logstash",
    "lora",
    "lorawan",
    "losant",
    "lte-m",
    "lua",
    "luajit",
    "lumen",
    "macos",
    "macos server",
    "mahalanobis distance",
    "malware",
    "manhattan distance",
    "mantis",
    "mapbox",
    "markdown",
    "markov chain monte carlo",
    "martini",
    "material design",
    "materialize",
    "matlab",
    "matplotlib",
    "mattermost",
    "maven",
    "maxcdn",
    "maxscript",
    "mbed os",
    "mcafee",
    "mdd",
    "mean shift",
    "mel",
    "mercurial",
    "mercurial distributed scm",
    "metal",
    "metasploit",
    "meteor",
    "meteor.js",
    "micro focus operations bridge",
    "micropython",
    "microsoft .net",
    "microsoft 365",
    "microsoft azure",
    "microsoft azure iot",
    "microsoft iis",
    "microsoft internet information services",
    "microsoft sql server",
    "microsoft teams",
    "milligram",
    "minio",
    "minio",
    "mint",
    "mithril",
    "mks integrity",
    "mobile accessibility",
    "mobile analytics",
    "mobile angular ui",
    "mobile app deployment",
    "mobile app design",
    "mobile app development best practices",
    "mobile app development blogs",
    "mobile app development books",
    "mobile app development communities",
    "mobile app development companies",
    "mobile app development conferences",
    "mobile app development courses",
    "mobile app development forums",
    "mobile app development frameworks",
    "mobile app development jobs",
    "mobile app development libraries",
    "mobile app development newsletters",
    "mobile app development platforms",
    "mobile app development podcasts",
    "mobile app development resources",
    "mobile app development tools",
    "mobile app development training",
    "mobile app development trends",
    "mobile app development websites",
    "mobile app distribution",
    "mobile app gamification",
    "mobile app internationalization",
    "mobile app localization",
    "mobile app maintenance",
    "mobile app marketing",
    "mobile app monetization",
    "mobile app personalization",
    "mobile app prototyping",
    "mobile app store optimization",
    "mobile app testing",
    "mobile app updates",
    "mobile app wireframing",
    "mobile performance optimization",
    "mobile security",
    "mobile user experience",
    "mobile user interface",
    "mocha",
    "mockito",
    "model deployment",
    "model driven development",
    "model evaluation",
    "model explainability",
    "model governance",
    "model interpretability",
    "model monitoring",
    "model performance",
    "model selection",
    "model serving",
    "monaca",
    "mongodb",
    "monkey http server",
    "mono",
    "monotone",
    "monotone version control system",
    "monte carlo simulation",
    "moogsoft",
    "mosquitto",
    "mpi",
    "mqtt",
    "mqtt.fx",
    "ms-dos",
    "mulesoft anypoint platform",
    "munin",
    "mvc",
    "mxnet",
    "myget",
    "mysql",
    "nagios",
    "naive bayes",
    "nat",
    "nativescript",
    "nb-iot",
    "ncsa httpd",
    "near field communication",
    "neat",
    "nec cloud",
    "neo4j",
    "nessus",
    "netbeans",
    "netbsd",
    "netdata",
    "netflow",
    "netlify",
    "netscape enterprise server",
    "nette",
    "network access control",
    "network access points",
    "network accounting",
    "network adapters",
    "network architecture",
    "network auditing",
    "network authentication",
    "network authorization",
    "network automation",
    "network business continuity",
    "network cables",
    "network capacity planning",
    "network compliance",
    "network configuration management",
    "network connectors",
    "network cost optimization",
    "network design",
    "network disaster recovery",
    "network discovery",
    "network documentation",
    "network encryption",
    "network energy efficiency",
    "network firewalls",
    "network function virtualization",
    "network gateways",
    "network governance",
    "network green computing",
    "network hubs",
    "network ids",
    "network incident response",
    "network interfaces",
    "network ips",
    "network load balancers",
    "network management",
    "network mapping",
    "network modems",
    "network monitoring",
    "network operations center",
    "network optimization",
    "network orchestration",
    "network performance monitoring",
    "network performance optimization",
    "network protocols",
    "network proxies",
    "network recovery",
    "network redundancy",
    "network resilience",
    "network risk management",
    "network routers",
    "network security",
    "network segmentation",
    "network social responsibility",
    "network standards",
    "network sustainability",
    "network switches",
    "network topology",
    "network traffic analysis",
    "network troubleshooting",
    "network vpns",
    "neural networks",
    "new relic",
    "next.js",
    "nextcloud",
    "nextcloud talk",
    "nexus",
    "nfc",
    "nginx",
    "nginx",
    "nginx unit",
    "nightwatch.js",
    "nim",
    "nimpy",
    "nltk",
    "node-red",
    "node.js",
    "nodemcu",
    "nokia cloud",
    "nomad",
    "non-negative matrix factorization",
    "nosql",
    "notepad++",
    "npm",
    "nuclio",
    "numba",
    "numpy",
    "nutanix acropolis",
    "nutanix xi cloud",
    "nuxt.js",
    "nw.js",
    "object oriented analysis and design",
    "object oriented programming",
    "objective-c",
    "observium",
    "ocaml",
    "office 365",
    "one-class svm",
    "onedrive",
    "onsen ui",
    "ooad",
    "oocss",
    "oop",
    "open shading language",
    "open source version control system",
    "openal",
    "openapi",
    "openbsd",
    "opencl",
    "opencv",
    "openebs",
    "openfaas",
    "opengl",
    "opengl es",
    "opengrok",
    "openhab",
    "openjdk",
    "openkm",
    "openlayers",
    "openlitespeed",
    "openmp",
    "opennebula",
    "opennms",
    "openresty",
    "openshift",
    "openshift container storage",
    "openshift origin",
    "openstack",
    "openstack magnum",
    "opensuse",
    "opentelemetry",
    "openthread",
    "openvpn",
    "openwhisk",
    "openwrt",
    "opnsense",
    "opsgenie",
    "opsview",
    "optics",
    "oracle cloud",
    "oracle cloud infrastructure",
    "oracle cloud infrastructure object storage",
    "oracle database",
    "oracle iplanet web server",
    "oracle jdk",
    "oracle kubernetes engine",
    "os/2",
    "osi model",
    "overfitting",
    "owncloud",
    "owncloud talk",
    "p4v",
    "packet loss",
    "padrino",
    "pagerduty",
    "pair programming",
    "palo alto networks",
    "pandas",
    "papertrail",
    "parcel",
    "particle",
    "particle cloud",
    "particle filters",
    "pascal",
    "pearson correlation",
    "penetration testing",
    "perforce",
    "perl",
    "pfsense",
    "phabricator",
    "phalcon",
    "phaser",
    "phishing",
    "phonegap",
    "php",
    "phpstorm",
    "phpunit",
    "pi-hole",
    "ping",
    "pingdom",
    "pl/sql",
    "plan 9",
    "plastic scm",
    "platformio",
    "platformio ide",
    "plotly",
    "plotly dash",
    "polymer",
    "pop3",
    "port forwarding",
    "portworx",
    "posix threads",
    "postgraphile",
    "postgresql",
    "postman",
    "postscript",
    "powershell",
    "preact",
    "precision",
    "precision-recall curve",
    "prettier",
    "principal component analysis",
    "prisma",
    "privoxy",
    "probabilistic graphical models",
    "problem driven development",
    "projectlocker",
    "prolog",
    "prometheus",
    "protocol buffers",
    "proton native",
    "protractor",
    "pubnub",
    "puppet",
    "pure.css",
    "push notifications",
    "pycharm",
    "pydio",
    "pygame",
    "pypy",
    "pyramid",
    "python",
    "python cpython",
    "python maya",
    "pytorch",
    "qingcloud",
    "qos",
    "qt",
    "quart",
    "quasar",
    "quay",
    "r",
    "racket",
    "rackspace",
    "rad",
    "radware",
    "raml",
    "rancher",
    "random forests",
    "ransomware",
    "rapid application development",
    "raspberry pi",
    "rational unified process",
    "raygun",
    "razorsync",
    "react",
    "react native",
    "react native admob",
    "react native android tv",
    "react native apple tv",
    "react native audio",
    "react native ble",
    "react native camera",
    "react native cli",
    "react native codepush",
    "react native crashlytics",
    "react native desktop",
    "react native elements",
    "react native facebook ads",
    "react native fast refresh",
    "react native firebase",
    "react native firebase analytics",
    "react native gifted chat",
    "react native google analytics",
    "react native hermes",
    "react native image picker",
    "react native in-app purchases",
    "react native macos",
    "react native maps",
    "react native material ui",
    "react native mobx",
    "react native navigation",
    "react native nfc",
    "react native paper",
    "react native push notifications",
    "react native redux",
    "react native router flux",
    "react native sentry",
    "react native turbo modules",
    "react native tv",
    "react native ubuntu",
    "react native vector icons",
    "react native video",
    "react native web",
    "react native webrtc",
    "react native windows",
    "react native windows tv",
    "reactos",
    "reasonml",
    "recall",
    "recurrent neural networks",
    "red hat ceph storage",
    "red hat cloudforms",
    "red hat enterprise linux",
    "red hat openshift",
    "red hat openshift container platform",
    "redis",
    "redmine",
    "regression analysis",
    "regularization",
    "reinforcement learning",
    "relay",
    "render",
    "renderscript",
    "requirejs",
    "resilio sync",
    "resin",
    "resin.io",
    "rest",
    "rest assured",
    "restful api",
    "revision control system",
    "rider",
    "riot",
    "riot os",
    "riot.js",
    "risc os",
    "risk management",
    "robot framework",
    "roc curve",
    "rocket.chat",
    "rollbar",
    "rollup",
    "rook",
    "routeros",
    "routing",
    "roxen web server",
    "rsa security",
    "rtos",
    "ruby",
    "ruby mri",
    "ruby on rails",
    "rubymine",
    "rubymotion",
    "rust",
    "rustpython",
    "safe",
    "sahi",
    "salesforce platform",
    "saltstack",
    "sanic",
    "sap cloud platform",
    "sapper",
    "sass",
    "sbt",
    "scala",
    "scala.js",
    "scaled agile framework",
    "scheme",
    "scikit-learn",
    "scikit-learn",
    "scipy",
    "scout",
    "scrapy",
    "scrum",
    "scrumban",
    "sd-wan",
    "sdl",
    "sdlc",
    "seaborn",
    "seafile",
    "security auditing",
    "security information and event management",
    "security operations center",
    "sed",
    "selenium",
    "semantic ui",
    "semaphore",
    "semi-supervised learning",
    "sencha touch",
    "sentry",
    "service oriented modeling",
    "servicenow",
    "servicenow itom",
    "sfml",
    "shaderlab",
    "shell",
    "shiny",
    "siem",
    "sigfox",
    "signal",
    "sikuli",
    "sinatra",
    "singular value decomposition",
    "site24x7",
    "skeleton",
    "skype",
    "slack",
    "slackware",
    "slim",
    "smacss",
    "smalltalk",
    "smtp",
    "snmp",
    "snort",
    "soap",
    "soapui",
    "soc",
    "social engineering",
    "socket.io",
    "software-defined networking",
    "software-defined perimeter",
    "solaris",
    "solarwinds orion",
    "sonarqube",
    "sonatype nexus",
    "sophos",
    "source code control system",
    "sourceanywhere",
    "sourceforge",
    "sourcegear vault",
    "sourcesafe",
    "sourcetree",
    "spacy",
    "spanning tree protocol",
    "spearman correlation",
    "spectral clustering",
    "spiral",
    "spiral model",
    "splunk",
    "spring",
    "spring boot",
    "spring framework",
    "spyder",
    "sql",
    "sqlite",
    "squid",
    "stacking",
    "statistical inference",
    "statuscake",
    "stencil",
    "stencil cli",
    "storageos",
    "storpool",
    "streamlit",
    "struts",
    "stylus",
    "sublime text",
    "subnetting",
    "subversion",
    "sucuri",
    "sumo logic",
    "sun java system web server",
    "supervised learning",
    "support vector machines",
    "surround scm",
    "survival analysis",
    "susy",
    "svelte",
    "svelte cli",
    "svg",
    "svn",
    "swagger",
    "swarm",
    "swift",
    "switching",
    "symantec",
    "symfony",
    "syncthing",
    "systems development life cycle",
    "t-sql",
    "tableau",
    "tailwind css",
    "tcp handshake",
    "tcp/ip",
    "team foundation server",
    "teamcity",
    "telegram",
    "tencent cloud",
    "tengine",
    "tensorflow",
    "tensorflow lite",
    "terraform",
    "test driven development",
    "testcafe",
    "testrail",
    "tfs",
    "thingsboard",
    "thingworx",
    "thread",
    "threat intelligence",
    "three.js",
    "threema",
    "throughput",
    "thttpd",
    "tibco cloud mashery",
    "time series analysis",
    "tinyos",
    "tomcat",
    "toml",
    "tonido",
    "tor",
    "tornado",
    "tortoisecvs",
    "tortoisegit",
    "tortoisesvn",
    "trac",
    "trace",
    "traceroute",
    "traefik",
    "transfer learning",
    "transformer",
    "travis ci",
    "trello",
    "trend micro",
    "turbogears",
    "tvos",
    "twilio",
    "twisted",
    "two-factor authentication",
    "tyk",
    "typescript",
    "ubidots",
    "ubuntu",
    "ucd",
    "ucloud",
    "ui",
    "ui automator",
    "uikit",
    "uml",
    "underfitting",
    "unified modeling language",
    "unified process",
    "unity",
    "unityscript",
    "unix",
    "unreal engine",
    "unsupervised learning",
    "upcloud",
    "uptimerobot",
    "user centered design",
    "uwsgi",
    "ux",
    "v-model",
    "v-model xt",
    "varnish",
    "vault",
    "vercel",
    "verizon cloud",
    "viber",
    "victorops",
    "vim",
    "virtual lan",
    "visual sourcesafe",
    "visual studio",
    "visual studio code",
    "visualsvn",
    "vmware cloud",
    "vmware tanzu kubernetes grid",
    "vmware vcloud air",
    "vmware vrealize operations",
    "vmware vsan",
    "voip",
    "vpn",
    "vs code",
    "vscode",
    "vss",
    "vue cli",
    "vue.js",
    "vulkan",
    "vulnerability assessment",
    "vulnerability scanning",
    "vultr",
    "vyos",
    "wasabi",
    "watchos",
    "waterfall",
    "web audio api",
    "web forms",
    "web midi api",
    "web speech api",
    "web2py",
    "webassembly",
    "webex",
    "webgl",
    "weblogic",
    "webpack",
    "webrtc",
    "websocket",
    "websockets",
    "webstorm",
    "wechat",
    "werkzeug",
    "whatsapp",
    "wildfly",
    "winappdriver",
    "wincvs",
    "windows",
    "windows api",
    "windows embedded",
    "windows iot",
    "windows server",
    "winsock",
    "wire",
    "wireguard",
    "wireless networking",
    "wiremock",
    "wireshark",
    "wsdl",
    "wso2 api manager",
    "wxwidgets",
    "xamarin",
    "xcode",
    "xcuitest",
    "xgboost",
    "xml",
    "xml schema",
    "xml-rpc",
    "xp",
    "xpath",
    "xquery",
    "yaml",
    "yarn",
    "yii",
    "z-wave",
    "zabbix",
    "zend",
    "zend framework",
    "zend studio",
    "zendesk",
    "zenoss",
    "zephyr",
    "zero trust networking",
    "zeus web server",
    "zig",
    "zigbee",
    "zipkin",
    "zoho projects",
    "zoho workplace",
    "zoom",
    "zorin os",
]
